import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>KLAS+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script>
          window.location.replace("https://play.google.com/store/apps/details?id=com.icecream.kwklasplus");
        </script>
      </Head>
    </>
  );
}
